/** A waiting service worker cannot interrupt a lesson; next visit activates it. */
import fs from 'node:fs/promises';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const root=new URL('../dist/',import.meta.url);let updated=false;
const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;const name=pathname==='/'?'index.html':pathname.slice(1);if(name.includes('..'))throw Error();let body=await fs.readFile(new URL(name,root));if(name==='sw.js'&&updated)body=Buffer.from(body.toString().replaceAll('pokelearn-shell-','pokelearn-shell-update-fixture-'));res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')||name.endsWith('.webmanifest')?'application/json':name.endsWith('.woff')?'font/woff':name.endsWith('.webp')?'image/webp':name.endsWith('.png')?'image/png':name.endsWith('.svg')?'image/svg+xml':'text/html');res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(4181,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true});
try{const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage();await page.goto('http://127.0.0.1:4181/?mock=1');await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);const old=await page.evaluate(()=>navigator.serviceWorker.controller.scriptURL);
await page.locator('#discover-plants').click();await page.locator('#tool-light').click();updated=true;await page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();await registration.update();});await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting);
assert.equal(await page.locator('#activityDialog').isVisible(),true);assert.equal((await page.evaluate(()=>window.__STUDIO_QA__.snapshot())).activity.solved,true);assert.equal(await page.evaluate(()=>navigator.serviceWorker.controller.scriptURL),old);await page.close();
const next=await context.newPage();await next.goto('http://127.0.0.1:4181/?mock=1');await next.waitForFunction(async()=> !(await navigator.serviceWorker.getRegistration()).waiting);await next.waitForFunction(async()=> (await caches.keys()).filter(k=>k.startsWith('pokelearn-shell-')).every(k=>k.includes('update-fixture')));await next.locator('#discover-plants').click();await next.locator('#tool-light').waitFor();console.log('PASS service-worker update waits through a lesson, activates on next visit and removes the old shell');await context.close();}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
