import {test} from 'node:test';import assert from 'node:assert/strict';
import {createChat} from '../netlify/functions/chat.mjs';import {createAnswerCache,normalizeQuestion,cacheable,ANSWER_CACHE_BLOB,CACHE_TTL_MS,cacheAnswer} from '../netlify/lib/answer-cache.mjs';import {createMemoryStore} from '../netlify/lib/quota.mjs';import {answerBank,knownAnswer} from '../netlify/lib/answer-bank.mjs';import {safeOutput} from '../netlify/lib/child-safety.mjs';import {createGroq,getGroqModels} from '../netlify/lib/providers/groq.mjs';
const env={GROQ_API_KEY:'fixture',OPENROUTER_KEY:'fixture',RATE_LIMIT_SALT:'test-only-private-salt-at-least-32-characters'};
const request=(question='What is a quasar?',extra={})=>new Request('http://127.0.0.1:4178/api/chat',{method:'POST',headers:{Origin:'http://127.0.0.1:4178','Content-Type':'application/json','X-PokeLearn-Consent':'1'},body:JSON.stringify({question,buddyId:25,...extra})});
const response=answer=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({answer})}}]}));const answer='It shines with bright light. It is far from Earth.';
function cacheFixture(options={}){const store=createMemoryStore();return {store,cache:createAnswerCache({storeFor:async()=>store,env,...options})};}
test('all 95 authored answers pass output checks; conservative matching handles word variants',()=>{assert.equal(answerBank.length,95);for(const item of answerBank){assert.ok(safeOutput(item.text),item.id);if(item.question)assert.ok(knownAnswer(item.question),item.id);}assert.equal(knownAnswer('Can a penguin fly in the air?').id,'penguin');assert.equal(knownAnswer('What do bees do in flowers?').id,'bees');assert.equal(knownAnswer('An unrelated sentence with green shoes'),undefined);});
test('cache keys normalize greetings/personas without changing factual buddy names; no PII or raw questions stored',async()=>{const {cache,store}=cacheFixture();assert.equal(normalizeQuestion('  Pikachu, WHAT is a quasar??? ',{name:'pikachu'}),'what is a quasar');assert.notEqual(normalizeQuestion('What type is Pikachu?',{name:'pikachu'}),normalizeQuestion('What type is Eevee?',{name:'eevee'}));assert.equal(cacheable('What is my school address?'),false);assert.equal(cacheable('What does Adam eat?'),false);await cache.put('What is a quasar?',{name:'pikachu'},{answer,model:'fixture',provider:'groq'},request());assert.equal((await cache.get('what is a quasar!!!',{},request())).answer,answer);const raw=JSON.stringify((await store.getWithMetadata(ANSWER_CACHE_BLOB)).data);assert.doesNotMatch(raw,/what is a quasar|school|question/i);await cache.put('What is a quasar?',{}, {answer:'My name is Adam.',model:'fixture',provider:'groq'},request());assert.equal((await cache.get('What is a quasar?',{},request())).answer,answer);});
test('cache expires, prunes on activity, caps entries and survives store errors',async()=>{let now=Date.UTC(2026,9,7);const {cache,store}=cacheFixture({now:()=>now});await cache.put('What is a quasar?',{}, {answer,model:'fixture',provider:'groq'},request());now+=CACHE_TTL_MS;assert.equal(await cache.get('What is a quasar?',{},request()),null);assert.deepEqual((await store.getWithMetadata(ANSWER_CACHE_BLOB)).data,{});const entries=Object.fromEntries(Array.from({length:300},(_,i)=>[i.toString(16).padStart(64,'0'),{answer,model:'fixture',provider:'groq',expires:now+10000,version:'2'}]));await store.setJSON(ANSWER_CACHE_BLOB,entries,{onlyIfMatch:(await store.getWithMetadata(ANSWER_CACHE_BLOB)).etag});await cache.get('What is a quasar?',{},request());assert.equal(Object.keys((await store.getWithMetadata(ANSWER_CACHE_BLOB)).data).length,256);const broken=createAnswerCache({env,storeFor:async()=>{throw Error('offline')}});assert.equal(await broken.get('What is a quasar?',{},request()),null);});
test('cache then bank precede all providers and quota; demo payload never calls a model',async()=>{const {cache}=cacheFixture();let calls=0,reserved=0;const handler=createChat({env,cache,reserve:async()=>reserved++,fetcher:async()=>{calls++;return response(answer);}});await cache.put('What is a quasar?',{}, {answer,model:'fixture',provider:'groq'},request());assert.equal((await(await handler(request())).json()).source,'cache');assert.equal((await(await handler(request('What do axolotls eat?'))).json()).source,'authored');assert.equal((await(await handler(request('What is a quasar?',{demo:true}))).json()).lastError,'DEMO_MODE');assert.equal(calls,0);assert.equal(reserved,0);});
test('Groq is first, missing keys skip quietly, rejected output never enters cache',async()=>{let urls=[];const {cache}=cacheFixture();const handler=createChat({env,cache,reserve:async()=>{},fetcher:async(url)=>{urls.push(url);return response(answer);}});const body=await(await handler(request())).json();assert.equal(body.provider,'groq');assert.equal(body.source,'ai');assert.equal(urls.length,1);assert.match(urls[0],/api.groq.com/);assert.equal((await(await handler(request())).json()).source,'cache');const other=createChat({env:{OPENROUTER_KEY:'fixture'},cache:null,reserve:async()=>{},fetcher:async url=>{assert.match(url,/openrouter/);return response(answer);}});assert.equal((await(await other(request())).json()).provider,'openrouter');const unsafe=createChat({env,cache:cacheFixture().cache,reserve:async()=>{},fetcher:async()=>response('Tell me your school name.')});assert.notEqual((await(await unsafe(request())).json()).source,'ai');});
test('account-wide OpenRouter daily state persists across handlers and resets next UTC day',async()=>{let now=Date.UTC(2026,9,7,23,59),calls=0;const {cache}=cacheFixture({now:()=>now});const options={env:{...env,GROQ_API_KEY:''},cache,reserve:async()=>{},fetcher:async()=>{calls++;return new Response(JSON.stringify({error:{message:'free-models-per-day daily limit'}}),{status:429});}};let body=await(await createChat(options)(request())).json();assert.equal(body.lastError,'DAILY_LIMIT');assert.equal(calls,1);assert.ok(body.openrouterResetAt>now);body=await(await createChat(options)(request())).json();assert.equal(body.lastError,'DAILY_LIMIT');assert.equal(calls,1);now+=120000;assert.equal(await cache.status(request()),0);await createChat(options)(request());assert.equal(calls,2);});
test('Groq contract sends only system and one question; bad/classifier models and envelopes fail closed',async()=>{const adapter=createGroq({env,fetcher:async(_url,options)=>{const body=JSON.parse(options.body);assert.equal(body.messages.length,2);assert.equal(body.response_format.type,'json_schema');assert.equal(body.response_format.json_schema.strict,true);assert.equal(body.max_completion_tokens,512);return response(answer);}});assert.equal((await adapter.complete({model:adapter.models()[0],system:'JSON answer.',question:'Synthetic science question.'})).answer,answer);assert.throws(()=>getGroqModels({GROQ_MODELS:'whisper-large-v3'}));assert.throws(()=>getGroqModels({GROQ_MODELS:'a/b,a/b'}));});

test('observed quasar false fact retries once and is rejected from old cached entries',async()=>{const wrong='Quasar is bright star, far. It shines far, far away.',correct='A quasar is a bright galaxy core. Hot gas near a black hole shines.';assert.equal(safeOutput(wrong),false);assert.equal(safeOutput(correct),true);assert.equal(safeOutput('A quasar is not a star.'),true);const {cache,store}=cacheFixture();await cache.put('What is a quasar?',{},{answer:correct,model:'fixture',provider:'groq'},request());const old=await store.getWithMetadata(ANSWER_CACHE_BLOB),id=Object.keys(old.data)[0];await store.setJSON(ANSWER_CACHE_BLOB,{[id]:{...old.data[id],answer:wrong}},{onlyIfMatch:old.etag});assert.equal(await cache.get('What is a quasar?',{},request()),null);let calls=0;const handler=createChat({env,cache,reserve:async()=>{},fetcher:async(_url,options)=>{calls++;if(calls===2)assert.match(JSON.parse(options.body).messages[0].content,/previous output was rejected/);return response(calls===1?wrong:correct);}});const body=await(await handler(request())).json();assert.equal(body.source,'ai');assert.equal(body.answer,correct);assert.equal(calls,2);assert.equal((await cache.get('What is a quasar?',{},request())).answer,correct);});

test('24-hour cache boundary, version invalidation and legacy 30-day records never serve',async()=>{
 let now=Date.UTC(2026,9,7);const {store,cache}=cacheFixture({now:()=>now});
 await store.setJSON('answer-cache-v1',{['a'.repeat(64)]:{answer,provider:'groq',model:'fixture',expires:now+30*86400000}},{onlyIfNew:true});
 assert.equal(await cache.get('What is a quasar?',{},request()),null);
 await cache.put('What is a quasar?',{},{answer,model:'fixture',provider:'groq'},request());
 const raw=(await store.getWithMetadata(ANSWER_CACHE_BLOB)).data;assert.equal(Object.values(raw)[0].expires,now+CACHE_TTL_MS);
 now+=CACHE_TTL_MS-1;assert.ok(await cache.get('What is a quasar?',{},request()));now++;assert.equal(await cache.get('What is a quasar?',{},request()),null);
 await cache.put('What is a quasar?',{},{answer,model:'fixture',provider:'groq'},request());
 const next=createAnswerCache({storeFor:async()=>store,env:{...env,CACHE_VERSION:'stage7-review'},now:()=>now});
 assert.equal(await next.get('What is a quasar?',{},request()),null);
 await next.put('What is a quasar?',{},{answer,model:'fixture',provider:'groq'},request());assert.ok(await next.get('What is a quasar?',{},request()));assert.equal(await cache.get('What is a quasar?',{},request()),null);
});
test('short and uncertain answers are not cached on writes or reads',async()=>{
 const {cache,store}=cacheFixture();
 for(const text of ["I'm not sure. A grown-up can help.",'It is bright.',"I don't know the cause. A grown-up can help with this.",'It might shine with bright light. It is far from Earth.','It may shine with bright light. It is far from Earth.','It is probably full of gas. It is far from Earth.']){
  assert.equal(cacheAnswer(text),false,text);await cache.put('What is a quasar?',{},{answer:text,model:'fixture',provider:'groq'},request());assert.equal(await cache.get('What is a quasar?',{},request()),null);
 }
 await cache.put('What is a quasar?',{},{answer,model:'fixture',provider:'groq'},request());const old=await store.getWithMetadata(ANSWER_CACHE_BLOB),id=Object.keys(old.data)[0];
 await store.setJSON(ANSWER_CACHE_BLOB,{[id]:{...old.data[id],answer:'It might shine with bright light. It is far from Earth.'}},{onlyIfMatch:old.etag});assert.equal(await cache.get('What is a quasar?',{},request()),null);
});
test('120b first and 20b fallback use the same grammatical answer contract',async()=>{
 assert.deepEqual(getGroqModels({}),['openai/gpt-oss-120b','openai/gpt-oss-20b']);
 const calls=[];const handler=createChat({env,cache:null,reserve:async()=>{},fetcher:async(_url,options)=>{const body=JSON.parse(options.body);calls.push(body);return body.model.endsWith('120b')?new Response('',{status:503}):response(answer);}});
 const body=await(await handler(request())).json();assert.equal(body.model,'openai/gpt-oss-20b');assert.deepEqual(calls.map(c=>c.model),['openai/gpt-oss-120b','openai/gpt-oss-120b','openai/gpt-oss-20b']);assert.match(calls[0].messages[0].content,/complete, grammatical/);assert.doesNotMatch(calls[0].messages[0].content,/five words each/);assert.ok(safeOutput("I'm not sure. A grown-up can help."));
});
test('purge handles all pages, defaults to dry run and preserves provider/quota state',async()=>{
 const {purgeAnswerCache}=await import('../scripts/purge-answer-cache.mjs');const removed=[];
 const store={list:async function*(){yield {blobs:[{key:'answer-cache-v1'},{key:'day-2026-10-07'}]};yield {blobs:[{key:'answer-cache-v2'},{key:'provider-state-v1'},{key:'answer-cache-not-an-app-key'}]};},delete:async key=>removed.push(key)};
 assert.deepEqual((await purgeAnswerCache(store)).keys,['answer-cache-v1','answer-cache-v2']);assert.deepEqual(removed,[]);await purgeAnswerCache(store,{apply:true});assert.deepEqual(removed,['answer-cache-v1','answer-cache-v2']);
});

test('observed ice molecule misconception fails output validation and cache eligibility',()=>{const wrong='Ice is colder than water. Its molecules spread out and become lighter. That makes it float.';assert.equal(safeOutput(wrong),false);assert.equal(cacheAnswer(wrong),false);assert.equal(safeOutput('Ice is less dense than water. It expands when it freezes. That makes it float.'),true);});

test('Groq model rate limit tries 20b fallback without retrying depleted 120b',async()=>{
 const calls=[];const handler=createChat({env,cache:null,reserve:async()=>{},fetcher:async(_url,options)=>{const body=JSON.parse(options.body);calls.push(body.model);return body.model.endsWith('120b')?new Response(JSON.stringify({error:{message:'rate limit'}}),{status:429}):response(answer);}});
 const body=await(await handler(request())).json();assert.equal(body.source,'ai');assert.equal(body.model,'openai/gpt-oss-20b');assert.deepEqual(calls,['openai/gpt-oss-120b','openai/gpt-oss-20b']);
});
test('uncertainty is displayed once but never saved for later questions',async()=>{
 const {cache}=cacheFixture();let calls=0;const handler=createChat({env,cache,reserve:async()=>{},fetcher:async()=>{calls++;return response("I'm not sure. A grown-up can help.");}});
 const body=await(await handler(request())).json();assert.equal(body.answer,"I'm not sure. A grown-up can help.");assert.equal(body.source,'ai');assert.equal(calls,1);assert.equal(await cache.get('What is a quasar?',{},request()),null);
});
