/** A delayed, maximum-sentence answer must not shift the voice dock. */
import assert from 'node:assert/strict';import {chromium} from 'playwright';
const base=process.env.POKELEARN_TEST_URL||'http://127.0.0.1:4178';const browser=await chromium.launch({headless:true});
try{for(const [label,width,height] of [['phone',390,844],['portrait',820,1180],['landscape',1180,820]]){
const p=await browser.newPage({viewport:{width,height},serviceWorkers:'block'});
await p.addInitScript(()=>{localStorage.setItem('pokelearn_voice_v3',JSON.stringify({consent:true}));window.shifts=[];new PerformanceObserver(list=>window.shifts.push(...list.getEntries().filter(e=>!e.hadRecentInput).map(e=>({value:e.value,sources:e.sources.map(s=>s.node?.id||s.node?.className)})))).observe({type:'layout-shift',buffered:true});});
await p.route('**/.netlify/functions/chat',async r=>{await new Promise(resolve=>setTimeout(resolve,1200));await r.fulfill({contentType:'application/json',body:JSON.stringify({answer:'Leaves use light to make their own food. Roots take in water from the soil. The water moves up inside the plant.',source:'ai',model:'fixture',code:'OK'})});});
await p.goto(base);await p.waitForFunction(()=>window.__STUDIO_QA__?.snapshot().catalog===1025);await p.locator('#keyboardButton').click();await p.locator('#questionInput').fill('Why do plants grow?');await p.locator('#questionForm button').click();await p.waitForFunction(()=>window.__STUDIO_QA__.snapshot().state==='speaking');await p.waitForTimeout(300);
const result=await p.evaluate(()=>{const text=document.querySelector('#captionText'),bubble=document.querySelector('.caption').getBoundingClientRect();return {cls:window.shifts.reduce((sum,e)=>sum+e.value,0),fits:text.scrollHeight<=text.clientHeight,overlappedProps:[...document.querySelectorAll('#sceneProps button')].filter(n=>n.getBoundingClientRect().bottom>bubble.top).map(n=>n.id)};});
assert.equal(result.cls,0);assert.equal(result.fits,true);assert.deepEqual(result.overlappedProps,[]);console.log('PASS delayed full-answer caption stability',label,JSON.stringify(result));
await p.locator('#changeBuddy').click();await p.locator('#buddySearch').fill('1025');await p.locator('#buddyGrid button').click();await p.locator('#buddyCharacter').evaluate(root=>root.replaceChildren());await p.locator('#discover-plants').click();await p.locator('#tool-light').waitFor();assert.equal(await p.locator('#activityBuddy').getAttribute('src'),null);assert.equal(await p.locator('#activityBuddy').evaluate(img=>getComputedStyle(img).visibility),'hidden');assert.match(await p.locator('#activityBuddyName').innerText(),/Pecharunt/);console.log('PASS missing artwork keeps the selected buddy identity',label);await p.close();
}}finally{await browser.close();}
