import assert from 'node:assert/strict';import {chromium} from 'playwright';
const base=process.env.POKELEARN_TEST_URL||'http://127.0.0.1:4178',browser=await chromium.launch();
try{
 const page=await browser.newPage({serviceWorkers:'block'});await page.addInitScript(()=>localStorage.setItem('pokelearn_voice_v3',JSON.stringify({consent:true})));
 const response=await page.goto(base);const headers=response.headers();assert.match(headers['content-security-policy'],/script-src 'self';/);assert.doesNotMatch(headers['content-security-policy'],/unsafe-eval|script-src[^;]*unsafe-inline/);assert.match(headers['content-security-policy'],/frame-ancestors 'none'/);assert.match(headers['permissions-policy'],/microphone=\(self\)/);assert.equal(headers['referrer-policy'],'no-referrer');assert.equal(headers['x-content-type-options'],'nosniff');
 await page.waitForFunction(()=>window.__STUDIO_QA__?.snapshot().catalog===1025);
 const state=await page.evaluate(async()=>{let blocked=0;document.addEventListener('securitypolicyviolation',()=>blocked++);const script=document.createElement('script');script.textContent='window.__unexpectedInline = true';document.body.append(script);await new Promise(r=>setTimeout(r,50));return {blocked,executed:!!window.__unexpectedInline};});assert.equal(state.executed,false);assert.ok(state.blocked>0);
 for(const [code,mode,line] of [['RESTING','resting',/rest/],['OFFLINE','offline',/offline/],['RATE_LIMITED','rate-limited',/rest/],['TYPE_INSTEAD','type-instead',/typing/]]){
  await page.route('**/.netlify/functions/chat',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code})}));await page.locator('#keyboardButton').click();await page.locator('#questionInput').fill('Why are leaves green?');await page.locator('#questionForm button').click();await page.waitForFunction(()=>window.__STUDIO_QA__.snapshot().state==='error');assert.equal(await page.locator('#main').getAttribute('data-error-state'),mode);assert.match(await page.locator('#captionText').innerText(),line);assert.equal(await page.locator('#keyboardButton').isEnabled(),true);await page.unroute('**/.netlify/functions/chat');
 }
 // Real local handlers, no mocked API route: blocked origin and sensitive input never need keys.
 const direct=await page.evaluate(async()=>{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-PokeLearn-Consent':'1'},body:JSON.stringify({question:'I am scared',buddyId:25})});return {status:response.status,body:await response.json(),cache:response.headers.get('cache-control')};});assert.equal(direct.status,200);assert.match(direct.body.answer,/glad you told me/);assert.match(direct.cache,/no-store/);
 const health=await (await page.request.get(base+'/api/health')).json();assert.deepEqual(Object.keys(health).sort(),['groq','openrouter','valsea']);assert.equal(typeof health.openrouter,'boolean');assert.equal((await page.request.post(base+'/api/chat',{data:{question:'Leaves?',buddyId:25}})).status(),403);assert.equal((await page.request.post(base+'/.netlify/functions/sentiment',{data:{transcript:'private'}})).status(),404);
 console.log('PASS enforced CSP/header policy, four friendly backend states, real local safeguarding/health routes, consent/origin rejection and removed sentiment endpoint');
}finally{await browser.close();}
