/** Ports v2 privacy, bounded-answer and cancellation checks onto the voice-first UI. */
import assert from 'node:assert/strict';import {chromium} from 'playwright';
const base=process.env.POKELEARN_TEST_URL||'http://127.0.0.1:4178';const browser=await chromium.launch({headless:true});
const snapshot=p=>p.evaluate(()=>window.__STUDIO_QA__.snapshot());
async function fresh(init){const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',serviceWorkers:'block'});const p=await context.newPage();await p.addInitScript(()=>localStorage.setItem('pokelearn_voice_v3',JSON.stringify({consent:true})));if(init)await p.addInitScript(init);await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__STUDIO_QA__?.snapshot().catalog===1025);return {context,p};}
async function type(p,text='Why do leaves need light?'){await p.locator('#keyboardButton').click();await p.locator('#questionInput').fill(text);await p.locator('#questionForm button').click();}
try{
const {context,p}=await fresh(()=>localStorage.setItem('pokelearn_history','old-private-question'));
assert.equal(await p.evaluate(()=>localStorage.getItem('pokelearn_history')),null);
const responses=['Leaves use light to make food.','Come back tomorrow.','Collect them all.','You lost.','Keep chatting.','Daily goals help you.','Turn on notifications.','These beautiful shiny leaves gently use bright sunlight daily.',''];let answer,captured;
await p.route('**/.netlify/functions/chat',r=>{captured=r.request().postDataJSON();return r.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content:answer}}]})});});
for(answer of responses){await type(p);await p.waitForFunction(()=>['error','speaking'].includes(window.__STUDIO_QA__.snapshot().state));assert.equal((await snapshot(p)).state,answer===responses[0]?'speaking':'error');assert.deepEqual(Object.keys(captured).sort(),['buddyId','question']);assert.equal(captured.buddyId,25);assert.equal(typeof captured.question,'string');assert.equal(await p.locator('#keyboardDialog').isVisible(),false);await p.locator('#micButton').click();}
assert.equal(await p.evaluate(()=>JSON.stringify(localStorage).includes('Why do leaves')),false);await context.close();console.log('PASS migration removes legacy question data; fresh question/ID-only requests; bounded answers reject pressure/long/empty output without histories or automatic follow-ups');
for(const action of ['stop','sleep','grownups','buddy']){
 const {context,p}=await fresh();let pending,release;await p.route('**/.netlify/functions/chat',r=>new Promise(resolve=>{pending=r;release=resolve;}));
 const sent=p.waitForRequest('**/.netlify/functions/chat');await type(p);await sent;
 if(action==='stop')await p.locator('#micButton').click();if(action==='sleep')await p.locator('#finish').click();if(action==='grownups')await p.locator('#grownupOpen').click();if(action==='buddy'){await p.locator('#changeBuddy').click();await p.locator('#buddySearch').fill('bulbasaur');await p.locator('#buddyGrid button').click();}
 await pending.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content:'LATE RESPONSE.'}}]})}).catch(()=>{});release();await p.waitForTimeout(100);
 assert.doesNotMatch(await p.locator('#captionText').innerText(),/LATE/);assert.equal((await snapshot(p)).requestActive,false);await context.close();
}
console.log('PASS late provider responses cannot undo Stop, Sleep, grown-up opening or buddy change');
const late=await fresh(()=>{window.__stopped=0;navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>window.__permission=resolve);});await late.p.locator('#micButton').click();assert.equal((await snapshot(late.p)).state,'permission');await late.p.locator('#finish').click();await late.p.evaluate(()=>window.__permission({getTracks:()=>[{stop:()=>window.__stopped++}]}));await late.p.waitForFunction(()=>window.__stopped===1);assert.equal((await snapshot(late.p)).recording,false);await late.context.close();console.log('PASS microphone permission arriving after Sleep releases its track');
const voices=await fresh(()=>{window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};window.__voiceCalls=[];speechSynthesis.getVoices=()=>[{lang:'en-US',localService:false}];speechSynthesis.speak=u=>window.__voiceCalls.push(u.text);});assert.equal(await voices.p.evaluate(()=>window.__voiceCalls.length),0);await voices.p.locator('#readAloud').click();assert.equal(await voices.p.evaluate(()=>window.__voiceCalls.length),0);assert.equal(await voices.p.locator('#captionText').isVisible(),true);await voices.p.evaluate(()=>{speechSynthesis.getVoices=()=>[{lang:'en-US',localService:true}];});await voices.p.locator('#readAloud').click();await voices.p.locator('#readAloud').click();assert.equal(await voices.p.evaluate(()=>window.__voiceCalls.length),1);await voices.p.reload({waitUntil:'domcontentloaded'});assert.equal((await snapshot(voices.p)).sound,false);await voices.context.close();console.log('PASS gesture-only local speech; unavailable/remote-only voices silently keep captions; audio off after reload');
const blocked=await fresh(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')};});await blocked.p.locator('#grownupOpen').click();const [a,b,c]=(await blocked.p.locator('#gateQuestion').innerText()).match(/\d+/g).map(Number);await blocked.p.locator('#gateAnswer').fill(String(a*b+c));await blocked.p.locator('#unlockSetup').click();await blocked.p.locator('#onlineConsent').check();assert.match(await blocked.p.locator('#consentStatus').innerText(),/this visit/);await blocked.p.keyboard.press('Escape');await blocked.p.locator('#discover-plants').click();await blocked.p.locator('#tool-light').waitFor();await blocked.context.close();console.log('PASS blocked storage remains a usable temporary visit');
}finally{await browser.close();}
